//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGitProj.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MrdDBEntities : DbContext
    {
        public MrdDBEntities()
            : base("name=MrdDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AddDoctrsDetail> AddDoctrsDetails { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Counrty> Counrties { get; set; }
        public virtual DbSet<MruserLogin> MruserLogins { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<SelectProduct> SelectProducts { get; set; }
        public virtual DbSet<Specialization> Specializations { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StateHQ> StateHQs { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<Territory> Territories { get; set; }
        public virtual DbSet<UserRegestraion> UserRegestraions { get; set; }
    }
}
