//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
namespace MyGitProj.DAL
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserRegestraion
    {
        public int RegId { get; set; }
        [Required (ErrorMessage ="Please Enter your First Name")]
        public string UserFirstName { get; set; }
        [Required(ErrorMessage = "Please Enter your Last Name")]
        public string UserLastName { get; set; }
        [Required(ErrorMessage = "Please Enter your Address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Please Enter your Phone No")]
        public string PhomeNumber { get; set; }
        [Required(ErrorMessage = "Please Enter your E-mail")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please Enter your Password")]
        [DataType(DataType.Password)]
        [StringLength(100, ErrorMessage = "Password \"{0}\" must have {2} character", MinimumLength = 8)]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{6,}$", ErrorMessage = "Password must contain: Minimum 8 characters atleast 1 UpperCase Alphabet, 1 LowerCase Alphabet, 1 Number and 1 Special Character")]
        public string Password { get; set; }
        [NotMapped]
        [Compare("Password",ErrorMessage = "Confirm password doesn't match, Type again !")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }
        [Required(ErrorMessage = "Please Enter your ZipCode")]
        public string ZipCode { get; set; }
        [Required(ErrorMessage = "Please Enter your State")]
        public Nullable<int> StateID { get; set; }
        [Required(ErrorMessage = "Please Enter your City")]
        public Nullable<int> CityID { get; set; }
    
        public virtual City City { get; set; }
        public virtual State State { get; set; }
    }
}
