//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyGitProj.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citie_table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citie_table()
        {
            this.UserRegestraions = new HashSet<UserRegestraion>();
        }
    
        public int CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<int> States { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRegestraion> UserRegestraions { get; set; }
    }
}
